/**
 * Author:  Nathan
 * Created: 27-Mar-2019
 */

-- jdbc:derby://localhost:1527/electronic_store_DB [nat on NAT]
-- database: electronic_store_DB
-- username: nat
-- password: nat

CREATE TABLE PRODUCTS (ID DECIMAL(20) NOT NULL, PRODUCT_NAME VARCHAR(100) NOT NULL, PRODUCT_PRICE DECIMAL(5, 2) NOT NULL, PRODUCT_TYPE VARCHAR(50) NOT NULL, PRIMARY KEY (ID));

INSERT INTO NAT.PRODUCTS (ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE) 
	VALUES (4102366650, 'Canon EOS 4000D DSLR Camera', 245.00, 'camera');
INSERT INTO NAT.PRODUCTS (ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE) 
	VALUES (5244245050, 'Vmotal GDC80X2 Mini Compact Digital Camera', 38.85, 'camera');
INSERT INTO NAT.PRODUCTS (ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE) 
	VALUES (6505226852, 'Garmin Vivoactive 3 GPS Smartwatch', 165.46, 'watch');
INSERT INTO NAT.PRODUCTS (ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE) 
	VALUES (3788276846, 'Audio-Technica ATH-S200BT Wireless On-Ear Headphones', 59.00, 'headphones');
INSERT INTO NAT.PRODUCTS (ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE) 
	VALUES (7624225586, 'Veho Zb-5 On-Ear Wireless Bluetooth Headphones', 59.95, 'headphones');

CREATE TABLE ORDERS (ORDER_NO INTEGER NOT NULL, CUSTOMER_NO INTEGER NOT NULL, "NAME" VARCHAR(255) NOT NULL, BILLING_ADDRESS VARCHAR(255) NOT NULL, CARD_TYPE VARCHAR(50) NOT NULL, TOTAL_PRICE DECIMAL(7, 2) NOT NULL, ORDER_DATE DATE NOT NULL, PRIMARY KEY (ORDER_NO));

INSERT INTO NAT.ORDERS (ORDER_NO, CUSTOMER_NO, "NAME", BILLING_ADDRESS, CARD_TYPE, TOTAL_PRICE, ORDER_DATE) 
	VALUES (973070, 390708, 'Blazer Man', '22 Orchird Avenue', 'credit', 243.16, '2019-03-23');
INSERT INTO NAT.ORDERS (ORDER_NO, CUSTOMER_NO, "NAME", BILLING_ADDRESS, CARD_TYPE, TOTAL_PRICE, ORDER_DATE) 
	VALUES (951603, 107203, 'Blazer Man', '22 Orchird Avenue', 'debit', 116.54, '2019-03-23');
INSERT INTO NAT.ORDERS (ORDER_NO, CUSTOMER_NO, "NAME", BILLING_ADDRESS, CARD_TYPE, TOTAL_PRICE, ORDER_DATE) 
	VALUES (194312, 130960, 'Nathan', '12 Uragway Way', 'debit', 194.25, '2019-03-26');
INSERT INTO NAT.ORDERS (ORDER_NO, CUSTOMER_NO, "NAME", BILLING_ADDRESS, CARD_TYPE, TOTAL_PRICE, ORDER_DATE) 
	VALUES (850901, 903012, 'Omar Peters', '99 Remington Road', 'debit', 116.54, '2019-03-23');
